# Generated by Django 2.1.3 on 2018-12-12 15:26

from django.conf import settings
import django.contrib.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181212_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=models.SET(django.contrib.auth.get_user_model), related_name='boxs2', to=settings.AUTH_USER_MODEL),
        ),
    ]
